# fly.toml app configuration file generated for bookrin on 2025-03-06T21:28:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bookrin'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  web = "bin/rails server"
  # websocket = "npm run start-websocket"

[[vm]]
  processes = ["web"]
  # Ruby3.3に必要なメモリ
  # https://community.fly.io/t/dockerfile-help-for-ruby-3-3-0/17700
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  processes = ["web"]
  internal_port = 3000
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

# [[services]]
#   processes = ["websocket"]
#   internal_port = 5678
#   protocol = "tcp"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
