name: Ruby

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  ruby:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: booklin_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test_password
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://test:test_password@localhost:5432/booklin_test'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop -a

      - name: Run slim-lint
        run: bundle exec slim-lint app/views -c .slim-lint.yml

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm ci

      - name: Start y-websocket
        run: HOST=localhost PORT=1234 npx y-websocket &

      - name: Run test
        run: bin/rails test:all
